<?php

namespace Z3d0X\FilamentFabricator\Resources;

use Filament\Resources\Concerns\Translatable;
use Z3d0X\FilamentFabricator\Models\TranslatablePage;
use Z3d0X\FilamentFabricator\Resources\TranslatablePageResource\Pages;

class TranslatablePageResource extends PageResource
{
    use Translatable;

    public static function getModel(): string
    {
        return TranslatablePage::class;
    }

    public static function getSlug(): string
    {
        return 'pages'; // TODO: Change the autogenerated stub
    }

    
    public static function getPages(): array
    {
        return [
            'index' => Pages\ListPages::route('/'),
            'create' => Pages\CreatePage::route('/create'),
            'view' => Pages\ViewPage::route('/{record}'),
            'edit' => Pages\EditPage::route('/{record}/edit'),
        ];
    }
}
